all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    #ansible_become: yes
    ansible_become_method: sudo 
  children:
    aws_ec2:
      hosts:
        testhost:
          user: admin 
          cfg_static_network: false
